JobAssigment/ViewModels/Home/IndexListItemViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JobAssigment.ViewModels.Home
{
    public class IndexListItemViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public bool? IsAcceptedTheJob { get; set; }

        public string OwnerName { get; set; }

        public string AssignedEmployeeName { get; set; }

        public DateTime DeadLine { get; set; }
    }
}

JobAssigment/ViewModels/Home/IndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JobAssigment.ViewModels.Home
{
    public enum JobStatus
    {
        Accepted, Declined, Pending
    }

    public class IndexViewModel
    {
        public bool IsAdmin { get; set; }

        public List<IndexListItemViewModel> IndexListItems { get; set; }

        public JobStatus SelectedStatus { get; set; }

        public IndexViewModel()
        {
            IndexListItems = new List<IndexListItemViewModel>();
            SelectedStatus = JobStatus.Pending;
        }
    }
}

JobAssigment/ViewModels/Job/CreateJobViewModel.cs
using JobAssigment.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JobAssigment.ViewModels.Job
{
    public class CreateJobViewModel
    {
        [Required]
        [MaxLength(20)]
        public string JobName { get; set; } //Munka elnevezése

        public string AssignedToEmployeeId { get; set; }

        public DateTime StartTheJob { get; set; } //Amikor kezdödik a munka

        public DateTime EndTheJob { get; set; } //Amikorra bekell fejezni a munkát

        public DateTime DeadLine { get; set; } //Munka lejárati ideje

        public List<SelectListItem> AvailableEmployees { get; set; }


        public CreateJobViewModel()
        {
            AvailableEmployees = new List<SelectListItem>();
        }
    }
}

JobAssigment/ViewModels/Job/EditViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JobAssigment.ViewModels.Job
{
    public class EditViewModel
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(20)]
        public string JobName { get; set; } //Munka elnevezése

        public string AssignedToEmployeeId { get; set; }

        public DateTime StartTheJob { get; set; } //Amikor kezdödik a munka

        public DateTime EndTheJob { get; set; } //Amikorra bekell fejezni a munkát

        public DateTime DeadLine { get; set; } //Munka lejárati ideje

        public List<SelectListItem> AvailableEmployees { get; set; }


        public EditViewModel()
        {
            AvailableEmployees = new List<SelectListItem>();
        }
    }
}

JobAssigment/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using JobAssigment.Models;
using Microsoft.AspNetCore.Identity;
using JobAssigment.Data;
using JobAssigment.Repository;
using JobAssigment.ViewModels.Home;
using System.Threading.Tasks;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using System.Collections;
using System.Collections.Generic;

namespace JobAssigment.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        RoleManager<IdentityRole> rolemanager; //szerepkörkezelő
        EmployeeUserManager usermanager; //felhasználókezelő
        IJobRepository jobRepository;

        public HomeController(RoleManager<IdentityRole> rolemanager,
           EmployeeUserManager usermanager, IJobRepository jobRepository)
        {
            this.usermanager = usermanager;
            this.rolemanager = rolemanager;
            this.jobRepository = jobRepository;
        }

        [HttpGet]
        public async Task<IActionResult> FirstStep()
        {
            //1. csinálunk egy admin szerepkört
            //2. beletesszük az első user-t

            IdentityRole adminrole = new IdentityRole()
            {
                Name = "admin"
            };
            await rolemanager.CreateAsync(adminrole);

            var firstuser = usermanager.Users.FirstOrDefault();

            await usermanager.AddToRoleAsync(firstuser, "admin");

            return RedirectToAction("Index");
        }

        public IActionResult Index()
        {
            bool isAdmin = User.IsInRole("admin");

            IndexViewModel model = new IndexViewModel();
            model.IsAdmin = isAdmin;

            IEnumerable<Job> filteredJobs = GetFilteredJobs(model.SelectedStatus, isAdmin);
            foreach (var item in filteredJobs)
            {
                model.IndexListItems.Add(MapJobEntityToIndexListViewModel(item));
            }

            return View("~/Views/Home/Index.cshtml", model);
        }

        [HttpPost]
        public IActionResult Filter(IndexViewModel model)
        {
            bool isAdmin = User.IsInRole("admin");

            IEnumerable<Job> filteredJobs = GetFilteredJobs(model.SelectedStatus, isAdmin);
            foreach (var item in filteredJobs)
            {
                model.IndexListItems.Add(MapJobEntityToIndexListViewModel(item));
            }

            return View("~/Views/Home/Index.cshtml", model);
        }

        public IActionResult Privacy()
        {
            return View("~/Views/Home/Privacy.cshtml");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


        private IEnumerable<Job> GetFilteredJobs(JobStatus jobStatus, bool isAdmin)
        {
            if (isAdmin)
            {
                return jobRepository.GetAll(jobStatus);
            }
            else
            {
                return jobRepository.GetAll(jobStatus)
                                    .Where(x => x.AssignedEmployeeId == usermanager.GetUserAsync(User)
                                                                                   .GetAwaiter()
                                                                                   .GetResult().Id);
            }
        }

        private IndexListItemViewModel MapJobEntityToIndexListViewModel(Job jobEntity)
        {
            return new IndexListItemViewModel
            {
                Id = jobEntity.Id,
                Name = jobEntity.Name,
                OwnerName = jobEntity.Owner?.UserName,
                AssignedEmployeeName = jobEntity.AssignedEmployee?.UserName,
                IsAcceptedTheJob = jobEntity.IsAcceptedTheJob,
                DeadLine = jobEntity.DeadLine
            };
        }
    }
}

JobAssigment/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JobAssigment.Data;
using JobAssigment.Models;
using JobAssigment.Repository;
using JobAssigment.ViewModels;
using JobAssigment.ViewModels.Home;
using JobAssigment.ViewModels.Job;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace JobAssigment.Controllers
{
    [Authorize]
    public class JobController : Controller
    {

        private readonly EmployeeUserManager _userManager;
        private readonly IJobRepository _jobRepository;

        public JobController(EmployeeUserManager userManager, IJobRepository jobRepository)
        {
            _userManager = userManager;
            _jobRepository = jobRepository;
        }

        [HttpGet]
        public IActionResult Create()
        {
            CreateJobViewModel model = new CreateJobViewModel()
            {
                DeadLine = DateTime.Now,
                StartTheJob = DateTime.Now,
                EndTheJob = DateTime.Now,
                AvailableEmployees = GetUsersForDropdown()
            };

            return View("~/Views/Job/CreateJob.cshtml", model);
        }

        [HttpPost]
        public IActionResult Create(CreateJobViewModel model)
        {
            if (ModelState.IsValid)
            {
                _jobRepository.Add(new Job
                {
                    Name = model.JobName,
                    StartTheJob = model.StartTheJob,
                    EndTheJob = model.EndTheJob,
                    DeadLine = model.DeadLine,
                    AssignedEmployeeId = model.AssignedToEmployeeId,
                    OwnerId = _userManager.GetUserId(User),
                    IsAcceptedTheJob = null
                });

                return RedirectToAction("Index", "Home");
            }

            model.AvailableEmployees = GetUsersForDropdown();
            return View("~/Views/Job/CreateJob.cshtml", model);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            _jobRepository.Remove(id);
            return RedirectToAction("Index", "Home");


        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var job = _jobRepository.GetByID(id);
            EditViewModel model = new EditViewModel
            {
                Id = id,
                StartTheJob = job.StartTheJob,
                EndTheJob = job.EndTheJob,
                DeadLine = job.DeadLine,
                JobName = job.Name,
                AssignedToEmployeeId = job.AssignedEmployeeId,
                AvailableEmployees = GetUsersForDropdown()
            };

            return View("~/Views/Job/Edit.cshtml", model);
        }

        [HttpPost]
        public IActionResult Edit(EditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.AvailableEmployees = GetUsersForDropdown();
                return View("~/Views/Job/Edit.cshtml", model);
            }
            var jobEntity = _jobRepository.GetByID(model.Id);
            jobEntity.Name = model.JobName;
            jobEntity.StartTheJob = model.StartTheJob;
            jobEntity.EndTheJob = model.EndTheJob;
            jobEntity.DeadLine = model.DeadLine;
            jobEntity.AssignedEmployeeId = model.AssignedToEmployeeId;

            _jobRepository.Update(jobEntity);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult DeclineJob(int id)
        {
            var jobEntity = _jobRepository.GetByID(id);
            jobEntity.IsAcceptedTheJob = false;
            _jobRepository.Update(jobEntity);

            return RedirectToAction("Index", "Home");
        }

        public IActionResult AcceptJob(int id)
        {
            var jobEntity = _jobRepository.GetByID(id);
            jobEntity.IsAcceptedTheJob = true;
            _jobRepository.Update(jobEntity);

            return RedirectToAction("Index", "Home");
        }

        private List<SelectListItem> GetUsersForDropdown()
        {
            return _userManager.Users.ToList().Where(x => !(_userManager.IsInRoleAsync(x, "admin")
                                                                          .GetAwaiter()
                                                                          .GetResult()))
                                                                          .Select(x => new SelectListItem
                                                                          {
                                                                              Text = x.UserName,
                                                                              Value = x.Id
                                                                          }).ToList();
        }
    }
}

JobAssigment/Controllers/JobDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using JobAssigment.Repository;
using JobAssigment.ViewModels.Home;
using JobAssigment.ViewModels.JobDetails;
using Microsoft.AspNetCore.Mvc;

namespace JobAssigment.Controllers
{
    public class JobDetailsController : Controller
    {
        private readonly IJobRepository _jobRepository;

        public JobDetailsController(IJobRepository jobRepository)
        {
            _jobRepository = jobRepository;
        }

        public IActionResult Index(int id)
        {
            var jobEntity = _jobRepository.GetByID(id);

            DetailsViewModel model = new DetailsViewModel
            {
                Id = id,
                AssignedEmployeeName = jobEntity.AssignedEmployee?.UserName,
                OwnerName = jobEntity.Owner?.UserName,
                Description = jobEntity.Description
            };

            return View("~/Views/JobDetails/Index.cshtml", model);
        }

        [HttpPost]
        public IActionResult AddDescription(DetailsViewModel model)
        {
            if (!ModelState.IsValid)
                return View("~/Views/JobDetails/Index.cshtml", model);

            var jobEntity = _jobRepository.GetByID(model.Id);
            jobEntity.Description = model.Description;
            _jobRepository.Update(jobEntity);

            return RedirectToAction("Index", "Home");
        }
    }
}

JobAssigment/Views/Home/Edit.cshtml
<h1>EDIT</h1>

JobAssigment/Views/Home/Index.cshtml
@model JobAssigment.ViewModels.Home.IndexViewModel
@using JobAssigment.ViewModels.Home

@{
    ViewData["Title"] = "Home Page";

    int rowCount = 1;
}


<form method="post" asp-controller="Home" asp-action="Filter" class="alert-light">
    <div class="form-group">
        <select class="form-control" asp-for="SelectedStatus">
            <option value="@JobStatus.Accepted" class="form-control">Accapted Job</option>
            <option value="@JobStatus.Declined" class="form-control">Declined Job</option>
            <option value="@JobStatus.Pending" class="form-control">Pending Job</option>
        </select>
    </div>


    <button type="submit" class="btn btn-primary" style="margin:10px">Filter</button>
</form>

<div class="alert-light">
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Job</th>
                <th scope="col">Owner (manager)</th>
                <th scope="col">Assigned to</th>
                <th scope="col">Deadline</th>
                <th scope="col">Assignee accepted</th>
                <th scope="col">Buttons</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var row in Model.IndexListItems)
            {
            <tr>
                <th scope="row">@Html.Raw((rowCount++).ToString())</th>
                <td>@row.Name  </td>
                <td>@row.OwnerName </td>
                <td>@row.AssignedEmployeeName </td>
                <td>@row.DeadLine.ToString("yyyy-MM-dd HH:mm")</td>
                <td class="align-content-lg-center" align="center">
                    @if (row.IsAcceptedTheJob.HasValue)
                    {
                    if (row.IsAcceptedTheJob.Value)
                    {
                    <i class="fas fa-check" ></i>
                    }
                    else
                    {
                    <i class="fas fa-times"></i>
                    }
                    }
                    else
                    {
                    <i class="fas fa-question"></i>
                    }

                </td>
                <td>
                    @if (Model.IsAdmin)
                    {


                    <a class="btn btn-warning" asp-controller="Job" asp-action="Edit" asp-route-id="@row.Id">
                        Edit
                    </a>
                    <a class="btn btn-danger" asp-controller="Job" asp-action="Delete" asp-route-id="@row.Id">
                        Delete
                    </a>
                    }
                    else if(!row.IsAcceptedTheJob.HasValue)
                    {
                    <a class="btn btn-primary" style="margin-right:10px" asp-controller="Job" asp-action="AcceptJob" asp-route-id="@row.Id">
                        Accept
                    </a>
                    <a class="btn btn-secondary" asp-controller="Job" asp-action="DeclineJob" asp-route-id="@row.Id" style="margin-right:10px">
                        Decline
                    </a>
                    }
                    <a class=" btn btn-primary" asp-controller="JobDetails" asp-action="Index" asp-route-id="@row.Id">
                        Details
                    </a>

                </td>
            </tr>
            }
        </tbody>
    </table>
</div>